Doc/personas
Interacao-Humano-Computador/2021.2-Prefeitura-Verdelandia pull request #20
Opened 2022-02-24 21:10 UTC by valdersonjr

Criação das personas e anti-persona.

2022-02-25 14:18 UTC, eliseukadesh67 requested changes

2022-02-25 14:18 UTC, eliseukadesh67 commented on docs/documentos/Personas.md
> +## 4. Referências
No lugar de referências, eu colocaira "Referências bibliograficas" como sugerido pelo professor.

2022-02-25 14:26 UTC, eliseukadesh67 reviewed
Faltou também colocar a página no mkdocs.yml.

2022-02-25 14:34 UTC, AntonioIgorCarvalho commented on docs/documentos/Personas.md
> +## 4. Referências
Alteração feita!

2022-02-25 16:53 UTC, eliseukadesh67 reviewed
Analisando a documentação como todo, acho que faltou explicar melhor qual foi a metodologia utilizado pra definir as Personas, qual a análise foi feita, quais ferramentas foram utilizadas, e creio que tem que haver uma concordância com o que foi definido em Perfi de Usuário.

2022-02-26 00:58 UTC, Ericklevy approved these changes
esta tudo certo pode mergar

2022-02-26 01:25 UTC, DouglasMonteles reviewed
- Não estaria faltando o tópico de Personas Secundárias?

- "O que torna essa persona como primária? e como secundária? e como antipersona?" - Síntese de uma pergunta feita pelo professor em uma apresentação que eu vi, então acho que é válido deixar isso bem claro ;)

2022-02-26 14:24 UTC, merged